# Generated by Django 5.2.12 on 2026-03-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='job_docs/'),
        ),
    ]
